---
- name: Remove existing routes
  ansible.builtin.command: "ip route del {{ item }}"
  loop: "{{ wireguard_client_route_subnets }}"
  ignore_errors: true

- name: Copy wireguard_routes.service file to remote host
  ansible.builtin.template:
    src: wireguard_routes.service.j2
    dest: /lib/systemd/system/wireguard_routes.service
    owner: root
    group: root
    mode: "0644"
  notify: Enable wireguard_routes.service