---
- name: Generate keys
  community.docker.docker_container_exec:
    container: "{{ service_name }}"
    command: "sh -c 'wg genkey | tee {{ item.name }}.private.key | wg pubkey > {{ item.name }}.public.key'"
    chdir: /config/wg_confs/

- name: Slurp the private key from the remote host
  ansible.builtin.slurp:
    src: "{{ wireguard_client_configs_directory }}/{{ item.name }}.private.key"
  register: private_key

- name: Copy client config files to the remote host
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "{{ wireguard_client_configs_directory }}/{{ item.name }}.conf"
    owner: 911
    group: 911
    mode: "0640"
  when: not wireguard_server_mode
  notify: Restart wireguard container