---
# handlers file for ansible-role-wireguard

- name: Restart wireguard container
  community.docker.docker_container:
    name: "{{ service_name }}"
    state: started
    restart: yes

- name: Enable wireguard_routes.service
  ansible.builtin.service:
    name: wireguard_routes
    daemon_reload: true
    enabled: true
    state: restarted